### ISSUE TITLE
求教两个疑惑

### ISSUE THREAD

**Issue by do-one-thing-to-well** [Dboy233/FragmentNavigatorHideShow#2]
首先感谢作者提供的思路，疑惑有二：
1.`NavHostFragment`的`createFragmentNavigator()`方法高版本已废弃了，有其他思路吗
2.`containerId`在false条件下的`nav_host_fragment_container`报错，根据备注理解是需要开发者自行填写Fragment容器布局的Id么。
麻烦了。

**Comment by Dboy233** [comment]
已经好久没研究这个了，等我回顾一下。

**Comment by Dboy233** [comment]
其实很久以前我就已经废弃使用HideShow了。我觉得还是完全按照ViewModel进行页面状态管理会更好一些。

**Comment by Dboy233** [comment]
@Silence-v 
1.createFragmentNavigator 源码的封装追踪都是通过 createFragmentNavigator创建的navigator . 所及即使被废弃了，也不妨碍。
2.containerId是你导航容器的id。不填写id当然会报错了。你看我demo怎么写的。。

可以查看我最新的提交。我更新了最新的导航框架依赖。如果你用的不是的话。根据我的修改内容，修改一下自己的版本。
最新的提交解决了一个，fragment打开自己的逻辑问题。
